version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 0
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
