name: Bug Report
description: File a bug/issue
title: '[bug] <title>'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    attributes:
      label: RainbowKit Version
      description: What version of RainbowKit are you using?
      placeholder: 1.0.0
    validations:
      required: true

  - type: input
    attributes:
      label: wagmi Version
      description: What version of wagmi are you using?
      placeholder: 1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior.
    validations:
      required: false

  - type: input
    attributes:
      label: Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)
      description: |
        This makes investigating issues and helping you out significantly easier! For most issues, you will likely get asked to provide one so why not add one now :)
      placeholder: https://codesandbox.io
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Browser info? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
